---

# ansible_connection: network_cli  # in case of ssh. telnet does not require this.
ansible_ssh_common_args: ""      # in case of ssh.

ansible_network_os: ios
ansible_user: cisco
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco
